---
title: "Demo 2 — Layout básico (fila)"
output:
  flexdashboard::flex_dashboard:
  orientation: rows
vertical_layout: fill
theme: cosmo
source_code: embed
---
  
  
  
```{r setup, include=FALSE, echo = F, message = F, warning = F}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = F}
library(flexdashboard)
library(leaflet)
library(ggplot2)
library(DT)
library(dplyr)
```

# Solapa 1 {data-width=40%}

## Indicadores clave

```{r, echo = F}

flexdashboard::valueBox(1200, caption = "Usuarios activos", icon = "fa-user", color = "primary")
flexdashboard::valueBox(88, "Satisfacción (%)", icon = "fa-smile", color = "success")
flexdashboard::valueBox(-4.2, "Variación mensual (%)", icon = "fa-chart-line",
                        color = ifelse(-4.2 >= 0, "success", "danger"))

```

# Solapa 2 {data-height=600}

## Serie de tiempo (paquete 'economics')

```{r, echo = F}

plotly::plot_ly(economics, x = ~date, y = ~uempmed, type = "scatter", mode = "lines") |>
  plotly::layout(title = "Duración de desempleo (mediana)")

```

